image: maven:latest

variables:
  #MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  #MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: ""
  MAVEN_OPTS: ""

#cache:
#  paths:
#    - .m2/repository/
#    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  image: maven:3.6-jdk-11
  script:
    - mvn $MAVEN_CLI_OPTS deploy -s ci_settings.xml
  only:
    - master
